[package]
name = "brygge"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
surrealdb = { version = "1.0.0", features = ["kv-mem", "kv-rocksdb"] }
tokio = { version = "1", features = ["full", "macros", "rt-multi-thread"] }
actix-web = "4"
actix-cors = "0.6.4"
ts-rs = "7.0.0"
uuid = "1.4.1"
mavlink = "0.12.0"
